## configuration file for running EVC

# EVC가 수행할 작업
activation: gradio # "train" or "pred" or "gradio"
# 클러스터 그룹명
group:
  - &group2 keti_test_rpi
# 작업을 수행할 노드
target:
  # *group1:
  # -   name: n02
  #     ip: evc.re.kr
  #     port: 33322
  #     hw: intel_NUC
  #     os: ubuntu
  #     gpu: RTX2080

  *group2:
  -   name: rpi6402
      ip: evc.re.kr
      port: 39002
      hw: rpi
      os: linux
      gpu: None

# 노드 소유자 명
owner: keti # host name

## AI 모델 정보
# 모델 이름
model_name: gradio-test # your_model
# 모델 버전
version: "3.0"
# 모델이 수행하는 태스크
task: detection # i.e. classification, segmentation
# 엣지 노드의 CPU 아키텍처
arch: x86_64 # i.e. x86_64, aarch64
# 학습 혹은 추론 대상 데이터
data: /home/plate_detection_data.yaml

